#关系型数据库配置
[mysql]
host = "8.130.73.119"
port = 3311
database = "douyin"
username = "root"
password = "dy12345678"
charset = "utf8mb4"
parse_time = true
loc = "Local"

#记录当前服务器的ip和启动端口号，当前服务器的ip用于生成对应的视频链接地址
[server]
ip = "localhost"
port = 8080
